import { LinePayApiClients } from '../payment-api/type';
import { EmptyObject, GeneralRequestConfig, GeneralResponseBody } from './type';
/** Request */
export declare type CheckPaymentStatusRequestParams = EmptyObject;
export declare type CheckPaymentStatusRequestConfig = GeneralRequestConfig & {
  /**
   * Payment transaction ID generated by LINE Pay
   */
  transactionId: string;
  /**
   * Request parameters of payment detail API
   */
  params: CheckPaymentStatusRequestParams;
};
/** Response */
export declare type Shipping = {
  /**
   * Shipping method ID selected by user
   */
  methodId: string;
  /**
   * Shipping fee
   */
  feeAmount: number;
};
export declare type Info = {
  /**
   * Shipping information
   */
  shipping?: Shipping;
};
export declare type CheckPaymentStatusResponseBody = GeneralResponseBody & {
  /**
   * Payment information
   */
  info?: Info[];
};
export declare const defaultTimeout = 20000;
export declare const checkPaymentStatusWithClient: LinePayApiClients['checkPaymentStatus'];
